clave: 12345678
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: ada
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ada
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: 'ant-path-matcher'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
